### ISSUE TITLE
No such file or directory - /home/redmine/redmine/Gemfile

### ISSUE THREAD

**Issue by ivn86** [bngsudheer/ansible-role-redmine#24]
https://github.com/bngsudheer/ansible-role-redmine/blob/ee631dcbbc9b3b74f5d4c0bbe6463ee9547c0f9c/tasks/main.yml#L138

`fatal: [192.168.23.245]: FAILED! => {"changed": false, "cmd": "/home/redmine/bin/bundler install --gemfile /home/redmine/redmine/Gemfile", "msg": "", "rc": 4, "stderr": "", "stderr_lines": [], "stdout": "\n[!] There was an error parsing `Gemfile`: No such file or directory - /home/redmine/redmine/Gemfile. Bundler cannot continue.\n", "stdout_lines": ["", "[!] There was an error parsing `Gemfile`: No such file or directory - /home/redmine/redmine/Gemfile. Bundler cannot continue."]}`

**Comment by bngsudheer** [comment]
What version of Ansible is this?

**Comment by ivn86** [comment]
ansible 2.5.0

**Comment by bngsudheer** [comment]
Did this error occur when you ran the playbook for the first time? Or did this occur after running the playbook repeatedly?

**Comment by ivn86** [comment]
Repeatedly. I restored the snapshot and ran playbook again, there were no more mistakes. I think you can close the issue.
